// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:2.1.0.0
//      SpecFlow Generator Version:2.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace Tests.Features
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.1.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [TechTalk.SpecRun.FeatureAttribute("HomePageModules", Description="\tIn order to have user friendly interface\r\n\tAs a product owner\r\n\tI want ebay home" +
        " page to show different modules in content", SourceFile="Features\\HomePageModules.feature", SourceLine=0)]
    public partial class HomePageModulesFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "HomePageModules.feature"
#line hidden
        
        [TechTalk.SpecRun.FeatureInitialize()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "HomePageModules", "\tIn order to have user friendly interface\r\n\tAs a product owner\r\n\tI want ebay home" +
                    " page to show different modules in content", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [TechTalk.SpecRun.FeatureCleanup()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public virtual void TestInitialize()
        {
        }
        
        [TechTalk.SpecRun.ScenarioCleanup()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void FeatureBackground()
        {
#line 7
#line 8
 testRunner.Given("I have navigated to home page of ebay", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
        }
        
        public virtual void HomePageModules_MenuWithTabsDisplayCorrectCategories(string categories, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "done"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("HomePageModules - Menu with tabs display correct categories", @__tags);
#line 11
this.ScenarioSetup(scenarioInfo);
#line 7
this.FeatureBackground();
#line 12
 testRunner.Then(string.Format("menu tab should show correct {0}", categories), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("HomePageModules - Menu with tabs display correct categories, Fashion", new string[] {
                "done"}, SourceLine=14)]
        public virtual void HomePageModules_MenuWithTabsDisplayCorrectCategories_Fashion()
        {
            this.HomePageModules_MenuWithTabsDisplayCorrectCategories("Fashion", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("HomePageModules - Menu with tabs display correct categories, Home & Garden", new string[] {
                "done"}, SourceLine=14)]
        public virtual void HomePageModules_MenuWithTabsDisplayCorrectCategories_HomeGarden()
        {
            this.HomePageModules_MenuWithTabsDisplayCorrectCategories("Home & Garden", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("HomePageModules - Menu with tabs display correct categories, Electronics", new string[] {
                "done"}, SourceLine=14)]
        public virtual void HomePageModules_MenuWithTabsDisplayCorrectCategories_Electronics()
        {
            this.HomePageModules_MenuWithTabsDisplayCorrectCategories("Electronics", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("HomePageModules - Menu with tabs display correct categories, Sports & Leisure", new string[] {
                "done"}, SourceLine=14)]
        public virtual void HomePageModules_MenuWithTabsDisplayCorrectCategories_SportsLeisure()
        {
            this.HomePageModules_MenuWithTabsDisplayCorrectCategories("Sports & Leisure", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("HomePageModules - Menu with tabs display correct categories, Collectables", new string[] {
                "done"}, SourceLine=14)]
        public virtual void HomePageModules_MenuWithTabsDisplayCorrectCategories_Collectables()
        {
            this.HomePageModules_MenuWithTabsDisplayCorrectCategories("Collectables", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("HomePageModules - Menu with tabs display correct categories, Health & Beauty", new string[] {
                "done"}, SourceLine=14)]
        public virtual void HomePageModules_MenuWithTabsDisplayCorrectCategories_HealthBeauty()
        {
            this.HomePageModules_MenuWithTabsDisplayCorrectCategories("Health & Beauty", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("HomePageModules - Menu with tabs display correct categories, Motors", new string[] {
                "done"}, SourceLine=14)]
        public virtual void HomePageModules_MenuWithTabsDisplayCorrectCategories_Motors()
        {
            this.HomePageModules_MenuWithTabsDisplayCorrectCategories("Motors", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("HomePageModules - Menu with tabs display correct categories, More", new string[] {
                "done"}, SourceLine=14)]
        public virtual void HomePageModules_MenuWithTabsDisplayCorrectCategories_More()
        {
            this.HomePageModules_MenuWithTabsDisplayCorrectCategories("More", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("HomePageModules - Category tab in menu has a drop down list with subcategories", new string[] {
                "done"}, SourceLine=24)]
        public virtual void HomePageModules_CategoryTabInMenuHasADropDownListWithSubcategories()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("HomePageModules - Category tab in menu has a drop down list with subcategories", new string[] {
                        "done"});
#line 25
this.ScenarioSetup(scenarioInfo);
#line 7
this.FeatureBackground();
#line 26
 testRunner.When("I hover \"Collectables\" category", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 27
 testRunner.Then("list of subcategories is displayed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("HomePageModules - Clicking on category tab redirects to correct page", new string[] {
                "done"}, SourceLine=29)]
        public virtual void HomePageModules_ClickingOnCategoryTabRedirectsToCorrectPage()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("HomePageModules - Clicking on category tab redirects to correct page", new string[] {
                        "done"});
#line 30
this.ScenarioSetup(scenarioInfo);
#line 7
this.FeatureBackground();
#line 31
 testRunner.When("I click \"Electronics\" category", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 32
 testRunner.Then("page redirects to  \"Electronics\" category page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("HomePageModules - Banner carousel\'s arrow navigates to different image on the lef" +
            "t", new string[] {
                "test"}, SourceLine=34)]
        public virtual void HomePageModules_BannerCarouselSArrowNavigatesToDifferentImageOnTheLeft()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("HomePageModules - Banner carousel\'s arrow navigates to different image on the lef" +
                    "t", new string[] {
                        "test"});
#line 35
this.ScenarioSetup(scenarioInfo);
#line 7
this.FeatureBackground();
#line 36
 testRunner.When("I click left arrow on carousel", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 37
 testRunner.Then("image changes", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("HomePageModules - Banner carousel\'s arrow navigates to different image on the rig" +
            "ht", SourceLine=38)]
        public virtual void HomePageModules_BannerCarouselSArrowNavigatesToDifferentImageOnTheRight()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("HomePageModules - Banner carousel\'s arrow navigates to different image on the rig" +
                    "ht", ((string[])(null)));
#line 39
this.ScenarioSetup(scenarioInfo);
#line 7
this.FeatureBackground();
#line 40
 testRunner.When("I click right arrow on carousel", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 41
 testRunner.Then("image changes", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.TestRunCleanup()]
        public virtual void TestRunCleanup()
        {
            TechTalk.SpecFlow.TestRunnerManager.GetTestRunner().OnTestRunEnd();
        }
    }
}
#pragma warning restore
#endregion
